name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            echo "Load Node environment"

            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            nvm use 22

            echo "Node:"
            node -v

            echo "NPM:"
            npm -v

            cd /var/www/emerald-dev-portfolio

            echo "Pull latest code"

            git reset --hard
            git pull origin main

            echo "Install dependencies"

            npm ci --include=optional

            echo "Remove old build"

            rm -rf dist

            echo "Build project"

            export NODE_OPTIONS="--max-old-space-size=4096"

            npm run build

            echo "Check build output"

            test -f dist/server/index.mjs

            echo "Restart PM2"

            pm2 restart emerald-portfolio --update-env

            pm2 save

            echo "Deploy success"