name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            cd /var/www/emerald-dev-portfolio

            echo "Pull latest code"

            git reset --hard
            git pull origin main

            echo "Install dependencies"

            npm ci --include=optional

            echo "Build project"

            export NODE_OPTIONS="--max-old-space-size=4096"

            npm run build

            echo "Validate build"

            test -f dist/server/index.mjs

            echo "Restart application"

            pm2 restart emerald-portfolio --update-env

            pm2 save

            echo "Deployment success"